### ISSUE TITLE
e2e spectron tests click on navbar buttons with no effect

### ISSUE THREAD

**Issue by Jazzepi** [Jazzepi/bunny-tracker#10]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%24150%20Rewarded-%237E24E3.svg" />](https://issuehunt.io/r/Jazzepi/bunny-tracker/issues/10)

https://github.com/Jazzepi/bunny-tracker/blob/master/e2e/main.spec.ts

The above file has this function in it. While the Spectron framework, using webdriver, can find the element, it can't click on it. Clicking works in the application itself, and it works in the window the e2e framework leaves up after a test failure. Success for this card is defined as being able to successfully click and navigate through the application.

Approaches I've already tried include.
1. Adding a very long timeout before the click.
2. Clicking on an element deeper in the dom.

```
it('should show add bunny page', async function () {
  await client.waitUntilWindowLoaded();
  // await client.pause(10000);
  // This doesn't work :(
  await client.click('[data-test="add-bunny-nav"] span');
  // await client.pause(1000);
  // client.getHTML('[data-test="add-bunny-nav"] span').then((thing) => {
  //   console.log(thing);
  // });
  // const addBunnyIsEnabled = await client.isEnabled('[data-test="add-bunny-nav"]');
  // expect(addBunnyIsEnabled).to.equal(true);
  //
  // const searchBunniesIsEnabled = await client.isEnabled('[data-test="search-bunnies-nav"]');
  // expect(searchBunniesIsEnabled).to.equal(false);
});

```

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $150.00)

- [<img src='https://avatars1.githubusercontent.com/u/2902740?v=4' alt='jazzepi' width=24 height=24> jazzepi](https://issuehunt.io/u/jazzepi) ($150.00)

### Submitted pull Requests
- [#11 done](https://issuehunt.io/r/Jazzepi/bunny-tracker/pull/11)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/Jazzepi/bunny-tracker/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by spiritbro1** [comment]
could you please elaborate more on this like after you click the button what do you want to check again?

**Comment by Jazzepi** [comment]
@spiritbro1 The application currently has two main tabs. The search bunny (the one you start on) and then add bunny. Once the add bunny nav button has been clicked, asserting that some element on the add bunny page should be visible would be fine, and the add bunny button should be highlighted.

The assertion isn't as important as getting the click to register.

**Comment by spiritbro1** [comment]
alright let me try this one i will create a draft pull request first

**Comment by spiritbro1** [comment]
hello i have create a draft pull request if you think its good i will open pull request so you can merge but there is something i need to modify feel free to say it to me i will edit it

**Comment by spiritbro1** [comment]
thank you sir you can close this issue i guess
